### ISSUE TITLE
<insert> is always inserting at index 0 and not using my toIndex value?

### ISSUE THREAD

**Issue by cajuncoding** [Bikeman868/UrlRewrite.Net#12]
Using the following condition and insert action I keep getting the resulting log and url output below:

For url http://localhost/channel/  I expect to be redirected to http://localhost/Channel/home.aspx

```
          <conditions logicalGrouping="MatchAny">
            <!-- NOTE: Since our Path trailing separator is always normalized (TOP of the Rewrite Rules) we can simplify
                        our logic to only check to see if more than 1 path element exists at this point (e.g. Channel/{something-else}),
                        and if not then we know we need to default to the Home page!
						-->
            <condition scope="pathElement" index="2" test="equals" ignoreCase="true" value="" />
          </conditions>
          <insert to="pathElement" toIndex="2" from="literal" fromIndex="home.aspx" />
          <action type="redirect" />

```

But I keep getting redirected to (backwards):
`http://localhost/home.aspx/channel`

And Debug logs are:

```
Rewrite:    0.2mS           rule 'Default Channel Home Page Rewrite Rule'
Rewrite:    0.2mS             list of 1 conditions
Rewrite:    0.2mS               request PathElement[2]='' Equals '' is true
Rewrite:    0.2mS             list of 1 conditions evaluated to true
Rewrite:    0.2mS             execute list of 2 actions
Rewrite:    1.7mS               insert "home.aspx" into PathElement before 0
Rewrite:    2.4mS               redirect to '/home.aspx/CCC' with 307 code
Rewrite:    2.4mS             finished executing actions. Stop processing
Rewrite:    2.4mS           rule 'Default Channel Home Page Rewrite Rule' was executed.  Stop processing. End request.
```

Where the insert element does not use the toIndex=2 -- or any other value I tried -- and always tries to insert at index 0 (zero)....

**Comment by Bikeman868** [comment]
Insert was intended for inserting into the middle of the path, moving other path elements to the right. I think if you ask it to insert beyond the last element it should just append. I will add some unit tests for this use case and fix any issues.
In the meantime since you are actually appending to the path you could switch your &lt;insert> for &lt;append>

**Comment by cajuncoding** [comment]
Actually insert is not working for any location for me, I tried to test it's behavior empirically also and found that it is always appending to index zero even if the index is in the middle of the path (e.g. I used longer fake paths to test).

In case it's helpful, the use case for me is simple, if no page is specified, then redirect to "home.aspx" as the default home page so that the new CMS based system is backwards compatible with the original legacy system.  So all I needed to do was test the path and then append "home.aspx".  But, it's been more difficult than I expected to sort out that simple syntax.

I agree, it would make intuitive sense that `<insert>` should just append if the index greater than the number of path elements, and `<append> ` should have the same behavior.  However, append currently throws an error:

```
for Url: /channel
I expected to get: /channel/home.aspx

```
But, I get this error:
`Index was out of range. Must be non-negative and less than the size of the collection.`

When I use configuration such as this:
`<append to="pathElement" toIndex="2" from="literal" fromIndex="home.aspx" />`

But I just now (today) found that it works if I use this (without any toIndex):
`<append to="pathElement" from="literal" fromIndex="home.aspx" />`

I hadn't tried that specific one yet.  

I would be great to add a small blurb into the documentation on the best way to add to the end of the path using pathElement, because if you append using from="path", then that wont' account for slashes/trimming, etc.  But pathElement is perfect for redirecting to a special page, etc.

As always, thanks for the prompt response!

**Comment by Bikeman868** [comment]
After reviewing the unit tests and the documentation I concluded that the current behaviour is correct. At the moment the insert and append actions behave differently and cover all possible needs. If I modified the insert action to append when referencing a non-existent path element we would lose some capability without gaining any new capabilities, because the append action already provides that already.
I updated the readme file to add more clarity around what the insert action does. Since you are adding to the end of the path you should definitely be using the append action.

**Comment by Bikeman868** [comment]
Thanks for the feedback. I think more documentation is needed here. For example

`<append to="pathElement" toIndex="2" from="literal" fromIndex="home.aspx" />`

Will append to path element 2, so that `/path1/path2/path3` will become `/path1/path2home.aspx/path3`

And the default toIndex is 0, and

`<append to="pathElement" toIndex="0" from="literal" fromIndex="home.aspx" />`

 is equivalent to 

`<append to="path" from="literal" fromIndex="home.aspx" />`

because path index 0 always refers to the whole path instead of just one path element. When you append to the path it will add a path separator if necessary.

You might also like to know that there is a syntactic shorthand for literals. Instead of writing 

`<append to="path" from="literal" fromIndex="home.aspx" />`

you can save some typing by writing

`<append to="path" value="home.aspx" />`

Martin.

**Comment by Bikeman868** [comment]
I updated the readme file. Please read it and let me know if this helps to make things clearer.
I also added unit tests for the `&lt;append>` action and found that it did not support negative indexing of path elements, so I fixed that and released a new version.

Thank you for helping to improve the quality of this project.

**Comment by cajuncoding** [comment]
Yes, this text that I now see (assume that it contains your updates) is much clearer and very helpful.  

![image](https://cloud.githubusercontent.com/assets/20844814/24085297/55a4763c-0cc7-11e7-866d-e3f9f6bba45b.png)

Before I read this I wasn't sure how to add a whole new path element to the end of the path.  To recap for anyone else that might see this thread:  insert was my first intuition, but couldn't insert to the end, and append seemed to only add to an existing value, and passing a path element index greater than the collection size failed.  This updated documentation really helps clarify that the code will handle this correctly by simply appending to the path (vs pathElement), and it will also handle inserting a path separator as needed, which was also a concern.

With this in mind, I  now see how the code supports core capabilities including those I was expecting in my use case:  insert a whole new path element into the middle, append to an existing path element value, and insert a whole new path elment to the beginning (index=1), and append a new path element ot the end (appent to path, not path element).  

One case that jumps out in my mind is what if the user wanted to pre-pend to an existing path element, instead of appending to the end?  I suppose they can use rewrite to do this, but would have to hardcode the value, and logic would likely be less dynamic.  

This is something to think about, as I'm not sure it's possible yet?

**Comment by Bikeman868** [comment]
A prepend action would be quite easy to write, but this seems to be a less commonly needed use case.

There is currently a regex replace ability (because this is provided by the Microsoft rewriter) which is even more flexible, even if a bit awkward to use.

**Comment by Bikeman868** [comment]
Almost a year since last comment
