### ISSUE TITLE
Adding rules Redirect Rules at Runtime

### ISSUE THREAD

**Issue by edgelandtech** [Bikeman868/UrlRewrite.Net#7]
I'm working on a Reverse Proxy based upon based upon a swagger definition.   We have several Azure based API Apps but want to an API Gateway to for end-clients so that they can access the API via a single URL such as API.ACME.NET/{conntroler}/Values.

I am able to extract all the calls via the swashbuckle generated swagger but would like to add the rewrite rules at runtime.

How would I do this with your package?

**Comment by Bikeman868** [comment]
My package does provide a way to load a new set of rules at runtime and swap them for the old set without losing any requests. Call the `LoadRules` method of the `RewriteModule` class to parse the rewrite rules and return `IRuleList` then call the `SetRules` method passing in the `IRuleList`.

If you want to dynamically create all of the rewrite rules in code rather than parsing them from XML, then you can also construct `IRuleList` in your code, or modify the one returned from `LoadRules` before passing it to `SetRules`.

If you don't want to have a rules file at all, then you can pass a `Stream` and an `IRuleParser` to the `Initialize` method of the `RewriteModule` class. In this case your parser will be responsible for constructing `IRuleList` from the `Stream`.

If what you are trying to do is none of these, then please explain in more detail what you meant by "add the rewrite rules at runtime".
